---
title: "Code Book"
author: "Jonathan Friedman"
date: "December 4, 2016"
output: html_document
---

## Codebook
  
The tidy.txt table produced containes 68 variables.
The first variable, Subject, refers to the subject that participated in the study.
The second variable, Activity, refers to one of six activities (walking, walking upstairs, walking downstairs, sitting, standing, laying).
The README file explains how these observations were made and the nature of the calculations.

The next 66 variables are interpreted as follows:
      
      * Each variable name begins with Time, referring to the time domain signals, or with Frequency, which refers to frequency domain signals.
      * The acceleration signal was separated into Body and Gravity acceleration signals, the next term.
      * The third element refers to the sensor signal: Accelerometer or Gryoscope.
      * The body linear acceleration and angular velocity were derived to obtain jerk signals, denoted by Jerk signals and Magnitude of three-dimensional signals   * The next element refers to the calculation, eiher Mean or STD, for standard deviation
      * For each, either the Mean or the STD was computed.
      * The final element is the axis along which the movement was made (X-axis, Y-axis, Z-axis)



Below is a list of the variable names.

```{r, echo = FALSE}    
library(reshape2)

setwd("C:/Users/yfriedman/Desktop/Coursera/Course 3/Week 4")

dftest_labels <- read.table("y_test.txt")
dftest_set <- read.table("X_test.txt")
dftrain_set <- read.table("X_train.txt")
dftrain_labels <- read.table("y_train.txt")
features <- read.table("features.txt")
subject_test <- read.table("subject_test.txt")
subject_train <- read.table("subject_train.txt")
activity_labels <- read.table("activity_labels.txt")

## merge training and test set to create new data set

merged_data <- rbind(dftrain_set, dftest_set)

## rename columns using features

colnames(merged_data) <- features$V2

## rbind train and test labels

merged_labels <- rbind(dftrain_labels, dftest_labels)

## cbind labels to merged data set

complete_data <- cbind(merged_labels, merged_data)

## rbind train and test subject

merged_subjects <- rbind(subject_train, subject_test)

## cbind  subjects to combined dataset

complete_data <- cbind(merged_subjects, complete_data)

## rename first columns with "Activity Name"

colnames(complete_data)[1] <- "Subject"
colnames(complete_data)[2] <- "Activity"

## determine columns that calculate mean and sd
## see README for explanation behind search term

index_meanstd <- grep("mean\\(|std\\(", names(complete_data))

## subset data for mean and std variables only

data_wanted <- complete_data[ ,c(1:2, index_meanstd)]

## introduce descriptive activity names

data_wanted$`Activity` <- factor(data_wanted$`Activity`, levels = activity_labels[,1], labels = activity_labels[, 2])

## clarify variable names

names(data_wanted) <- gsub("-mean()", "Mean", names(data_wanted), fixed = TRUE)
names(data_wanted) <- gsub("-std()", "STD", names(data_wanted), fixed = TRUE)
names(data_wanted) <- gsub("-X", "X-axis", names(data_wanted))
names(data_wanted) <- gsub("-Y", "Y-axis", names(data_wanted))
names(data_wanted) <- gsub("-Z", "Z-axis", names(data_wanted))
names(data_wanted) <- gsub("^t", "Time ", names(data_wanted))
names(data_wanted) <- gsub("^f", "Frequency ", names(data_wanted))
names(data_wanted) <- gsub("Acc", " Accelerometer ", names(data_wanted))
names(data_wanted) <- gsub("Gyro", " Gyroscope", names(data_wanted))
names(data_wanted) <- gsub("Mag", " Magnitude ", names(data_wanted))
names(data_wanted) <- gsub("Jerk", " Jerk ", names(data_wanted))
print(names(data_wanted))
```

